import Footer from "@/components/layouts/Footer";
import Navbar from "@/components/layouts/Navbar";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const myBangla = localFont({
  src: "../fonts/mayaboti-normal.ttf",
  // weight: "",
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}} antialiased`}>
        <header className="py-2 md:w-11/12 mx-auto">
          <Navbar />
        </header>
        <main className="py-2 px-1 md:w-11/12 mx-auto min-h-[calc(100vh-310px)]">
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
